<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="DeleteBooks.aspx.cs" Inherits="Practical4ii.DeleteBooks" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <h1>Delete Book</h1>
        <table>
            <tr>
                <td>Select ISBN to delete:</td>
                <td>
                    <asp:DropDownList ID="ddlISBN" runat="server" 
                        DataTextField="ISBN" DataValueField="ISBN" AutoPostBack="True" 
                        SelectMethod="BindISBN" AppendDataBoundItems="true">
                        <asp:ListItem Value="0">Select One:</asp:ListItem>
                    </asp:DropDownList></td>
                
            </tr>
        </table>

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [Books]"></asp:SqlDataSource>

        <br />
        <asp:DetailsView ID="dvDeleteBook" runat="server" Height="50px" Width="125px"
            ItemType="Practical4ii.Models.Book"
            DataKeyNames="ISBN"
            SelectMethod="BindBookDetails"
            DeleteMethod="DeleteBookDetails"
            AutoGenerateDeleteButton="True">
        </asp:DetailsView>
    </form>

    <br />

    <asp:HyperLink ID="hpMenu" runat="server" NavigateUrl="~/Menu.aspx">Back to Menu</asp:HyperLink>
</body>
</html>
